export const controls = {
  boxShadow: {
    inputs: {
      xOffset: {
        label: "X-Offset",
        parameter: "xOffset",
        min: -100,
        max: 100,
        step: 1,
        defaultValue: 0,
        type: "range",
        unitType: "px",
      },
      yOffset: {
        label: "Y-Offset",
        parameter: "yOffset",
        min: -100,
        max: 100,
        step: 1,
        defaultValue: 0,
        type: "range",
        unitType: "px",
      },
      blur: {
        label: "Blur",
        parameter: "blur",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 0,
        type: "range",
        unitType: "px",
      },
      spread: {
        label: "Spread",
        parameter: "spread",
        min: -100,
        max: 100,
        step: 1,
        defaultValue: 0,
        type: "range",
        unitType: "px",
      },
      color: {
        label: "Color",
        parameter: "color",
        defaultValue: "#181818",
        type: "color",
      },
      opacity: {
        label: "Opacity",
        parameter: "opacity",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 100,
        type: "range",
        unitType: "%",
      },
    },
  },
  linearGradient: {
    inputs: {
      angle: {
        label: "Angle",
        parameter: "angle",
        min: 0,
        max: 360,
        step: 1,
        defaultValue: 180,
        type: "range",
        unitType: "px",
      },
    },
  },
}
